Repository GSG-G11/TasksTracker, pull requests merged in 2022-03, with the labels that each got.

#14 create add todo modal form
  src/components/models/AddTodoForm.jsx
Labels: Awaiting Review

#17 create todo card
  .eslintrc.json
  public/index.html
  src/App.css
  src/App.jsx
  src/components/TodoCard.jsx
Labels: Awaiting Review

#19 delete tasks
  src/App.js
Labels: Approved

#20 edit task
  src/App.css
  src/App.js
  src/components/CardsContainer.jsx
  src/components/Header.jsx
Labels: Done

#25 1 readme file
  README.md
Labels: Awaiting Review

#26 done functionality
  src/App.css
  src/App.js
  src/components/CardsContainer.jsx
  src/components/TodoCard.jsx
Labels: Done

#27 react v18 compatibility
  public/manifest.json
  src/index.js
Labels: Awaiting Review
